# Generated by Django 4.2 on 2024-09-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_myuser_work_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='work_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
